"""UpdateLandmark

Revision ID: 64eafcc91fa4
Revises: 13fce09df3e6
Create Date: 2018-02-21 22:36:55.562685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eafcc91fa4'
down_revision = '13fce09df3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('landmarks_city_id_fkey', 'landmarks', type_='foreignkey')
    op.create_foreign_key(None, 'landmarks', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landmarks', type_='foreignkey')
    op.create_foreign_key('landmarks_city_id_fkey', 'landmarks', 'landmarks', ['city_id'], ['id'])
    # ### end Alembic commands ###
