"""empty message

Revision ID: 66663e4a441a
Revises: 
Create Date: 2018-03-31 20:14:33.031439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66663e4a441a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boroughs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('date_designated', sa.DateTime(), nullable=True),
    sa.Column('borough_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['borough_id'], ['boroughs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landmarks')
    op.drop_table('boroughs')
    # ### end Alembic commands ###
